Update bool.h
C23 introduces the bool literal, this causes compilation breakage here.

```
bool.h:35:27: error: 'bool' cannot be defined via 'typedef'
   35 |     typedef unsigned char bool;
      |                           ^~~~
bool.h:35:27: note: 'bool' is a keyword with '-std=c23' onwards
```